name = "MieScattering"
uuid = "2617ce25-9e41-4542-aef8-d53ddee1fd97"
authors = ["Oliver Kliebisch <oliver@kliebisch.net> and contributors"]
version = "1.0.4"

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Polyester = "0.6, 0.7"
PrecompileTools = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
