name = "MieScattering"
uuid = "2617ce25-9e41-4542-aef8-d53ddee1fd97"
authors = ["Oliver Kliebisch <oliver@kliebisch.net> and contributors"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
