name = "MieScattering"
uuid = "2617ce25-9e41-4542-aef8-d53ddee1fd97"
authors = ["Oliver Kliebisch <oliver@kliebisch.net> and contributors"]
version = "0.1.2"

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
Polyester = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
